version: "3.8"

services:
  susi:
    image: ghcr.io/chrisshikayri/chururu:latest
    build: .
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.susi.entrypoints=http"
        - "traefik.http.routers.susi.rule=Host(`susi.byronrm.com`)"
        - "traefik.http.middlewares.susi-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.susi.middlewares=susi-https-redirect"
        - "traefik.http.routers.susi-secure.entrypoints=https"
        - "traefik.http.routers.susi-secure.rule=Host(`susi.byronrm.com`)"
        - "traefik.http.routers.susi-secure.tls=true"
        - "traefik.http.routers.susi-secure.tls.certresolver=http"
        - "traefik.http.routers.susi-secure.service=susi"
        - "traefik.http.services.susi.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true